"""
Future Blender worker entrypoint (inactive in MVP Option A).
Active runtime uses handler.py via uvicorn in Dockerfile.
"""

from __future__ import annotations

import json
import os
import subprocess
import tempfile
import time
from pathlib import Path

from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel


class UvJobRequest(BaseModel):
    user_id: str
    wardrobe_item_id: str
    category: str
    garment_prompt: str
    color: str
    brand: str
    base_model_id: str
    generation_mode: str = "fast_uv"


app = FastAPI(title="SAI Blender UV Worker")


@app.post("/jobs")
def create_job(payload: UvJobRequest, authorization: str | None = Header(default=None)):
    expected_token = os.getenv("BLENDER_WORKER_TOKEN", "").strip()
    if expected_token:
        if not authorization or authorization != f"Bearer {expected_token}":
            raise HTTPException(status_code=401, detail="Unauthorized")

    blender_bin = os.getenv("BLENDER_BIN", "blender")
    scene_dir = Path(os.getenv("BLENDER_SCENE_DIR", "./scenes"))
    output_dir = Path(os.getenv("BLENDER_OUTPUT_DIR", "./output"))
    output_dir.mkdir(parents=True, exist_ok=True)

    scene_path = scene_dir / f"{payload.base_model_id}.blend"
    if not scene_path.exists():
        raise HTTPException(status_code=400, detail=f"Base scene not found: {scene_path}")

    started = time.time()
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
      json.dump(payload.model_dump(), f)
      job_file_path = Path(f.name)

    worker_entry = Path(__file__).with_name("worker_entry.py")
    cmd = [
        blender_bin,
        "-b",
        str(scene_path),
        "--python",
        str(worker_entry),
        "--",
        "--job-json",
        str(job_file_path),
        "--output-dir",
        str(output_dir),
    ]

    completed = subprocess.run(cmd, capture_output=True, text=True)
    if completed.returncode != 0:
        raise HTTPException(
            status_code=500,
            detail={
                "error": "blender_failed",
                "stdout": completed.stdout[-1500:],
                "stderr": completed.stderr[-1500:],
            },
        )

    result_path = output_dir / f"{payload.wardrobe_item_id}_result.json"
    if not result_path.exists():
        raise HTTPException(status_code=500, detail="Result artifact not generated by Blender worker")

    result_payload = json.loads(result_path.read_text(encoding="utf-8"))
    total_ms = int((time.time() - started) * 1000)
    return {
        "stage": "completed",
        "artifacts": result_payload.get("artifacts", {}),
        "metrics": {
            "totalMs": total_ms,
            **result_payload.get("metrics", {}),
        },
    }
