import type { Metadata } from "next";
import "./globals.css";
import { shareTechMono } from "./fonts";
// ❌ REMOVER esta linha:
// import SiteLanguageBridge from "@/app/components/i18n/SiteLanguageBridge";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${shareTechMono.variable} min-h-screen antialiased`}>
        {/* ❌ REMOVER esta linha: */}
        {/* <SiteLanguageBridge /> */}
        {children}
        </body>
        </html>
    );
}